Just like numpy ufuncs, Broadcasting can be used to vectorize operations to bypass Python's type checking. Broadcasting is a set of rules for applying binary ufuncs on arrays of different sizes.

Broadcasing allows for binary operations to be performed on arrays of different sizes, for example, a scalar (zero dimensional array) can be added to an array

In [1]:
import numpy as np
a = np.array([0, 1, 2])
a + 5

array([5, 6, 7])

The '5' is essentially stretched into an an array([5, 5, 5]) and adds the results. The advantage of this is that the duplication of values doesn't actually happen, which saves on compute resources.

This can also be done along multidimensional arrays and can even involve both arrays being broadcasted.

In [4]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

There are a couple rules that go into broadcasting
 - Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
 - Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
 - Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.