Fancy indexing means an array of indexes can be indexed in an array to get an array of values corresponding to the array of indexes

In [9]:
import numpy as np

rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


If we want to get the values at index 3, 5 and 7, we can index an array of the desired indexes:

In [10]:
x[[3,5,7]]

array([71, 20, 86])

This also works with multi dimensional arrays

In [11]:
x = np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
row = np.array([0,1,2])
col = np.array([2,1,3])
x[row,col]

array([ 2,  5, 11])

Fancy indexing can be combined with regular indexing,slicing and masking

In [13]:
x[2,[2,0,1]]  # with regular indexing
x[1:,[2,0,1]]  # slicing

array([10,  8,  9])

One common application for fancy indexing is to visualize changes in comaprison to the original data