## Why Arrays are important

Everything can be broken down into arrays. Images for example can be broken down into a two dimensional array of numbers representing pixel brightness and audio can be broken down into a one dimensional array of intensity versus time. Therefore, the efficient storage and manipulation of arrays is key to data science. This is where NumPy comes in. 

NumPY is an interface to store and operate on dense data buffers. Unlike Python's list type, Numpy provides much more efficient storage and data opereations as the array grows larger.

In [5]:
import numpy as np

# Get version
np.__version__

# np? to view documentation

'1.20.3'

## Data types

Since every variable in Python is dynamically typed, it is alot more easier to work with than a statically typed language like C. However, this flexibility is a double edged sword, since Python variables are more than the value of that variable itself, they contain information about that value's type. 

One way to summarize this would be to say that every variable in Python is an object. This means that there is some more overhead compared to a language like C, where an integer is the raw integer itself. Likewise, an list of Python integers creates an increasing amount of overhead as the list grows ever larger since each of it's component integers has it's own metadata regarding that integer.

## Creating Numpy Arrays

Numpy arrays can be created from regular python lists:

In [10]:
first = [0, 1, 2, 3, 4]
np.array(first)

array([0, 1, 2, 3, 4])

In [11]:
# Numpy will upcast if types don't match
second = [0, 1, 1.987, 2, 3, 3.14, 4]
np.array(second)

array([0.   , 1.   , 1.987, 2.   , 3.   , 3.14 , 4.   ])

In [12]:
# Creating a multidimensional array using lists
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

They can also be created from scratch

In [14]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Numpy Array Basics